### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Cherkah** [microhacker07/vnstat-dashboard#1]
hi
nothing hapens when launching `python3 Server.py`
in the terminal i have somting for these cmd :
`python3 -m http.server 8000 --bind 127.0.0.1
python3 -m http.server`

so what's wrong?
PS: on manjaro nothing correspond to the package plotlyjs (in repository)

**Comment by nebock** [comment]
Hello!
Thank you for mentioning that! I forgot to update the instructions. You should be able to run the server with `python3 main.py`
Also you can edit the `main.py` and change the port that bottle uses if you want.

As for the Ploty JS library. It is grabbed from [https://cdn.plot.ly/plotly-latest.min.js](https://cdn.plot.ly/plotly-latest.min.js) by the web browser (seen in public/index.html) and used by the JavaScript on the client side. No need to install anything for plotly. Just mentioned it as I use the library for graphing the data

Hopes that clears it up!

**Comment by mu-us61** [comment]
it works perfectly thanks, offical one did not work (it was last updated 2 years ago) but this one works, but your nickname is intimidating microhacker07 i had to check the source code lol xD

**Comment by nebock** [comment]
Nice that it is working (and not just on my machine and pi)! From what I can tell the official dashboard should work with the latest version of vnstat as the json only changed from 1.x to 2.x. I just had a lot of trouble getting it (and mostly docker) to run on my pi so I just made my own dashboard in python and javascript. Nice to know that other people are using my code :).
